name: bet
description: Join The BullRun
authors:
  - Programmer <Sajjadjavadi28@gmail.com>
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  line_icons: ^2.0.1
  responsive_framework: ^0.2.0
  dio: ^4.0.6
  url_launcher: ^6.1.5
  intl: ^0.17.0
  get_storage: ^2.0.3
  socket_io_client: ^2.0.0
  url_strategy: ^0.2.0
  flutter_svg: ^1.1.1+1
  flutter_web3: ^2.1.9
  audioplayers: ^1.0.1
  nil: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/video/
    - assets/sound/
    - assets/

  fonts:
    - family: gilroy
      fonts:
        - asset: assets/fonts/gilroy.ttf
          weight: 400
        - asset: assets/fonts/gilroy-bold.ttf
          weight: 700
